// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231027114355_pushModelsToDataBase")]
    partial class pushModelsToDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.BuyTranscation", b =>
                {
                    b.Property<int>("TranscationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranscationId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("CoinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoinImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerCoin")
                        .HasColumnType("float");

                    b.Property<DateTime>("TrascationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TranscationId");

                    b.ToTable("buyTranscations");
                });

            modelBuilder.Entity("webapi.Models.SellTranscation", b =>
                {
                    b.Property<int>("TranscationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranscationId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("CoinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoinImageURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerCoin")
                        .HasColumnType("float");

                    b.Property<DateTime>("TranscationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TranscationId");

                    b.ToTable("sellTranscations");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapi.Models.UserAsset", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("CoinCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("CoinImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAssetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CoinCode");

                    b.ToTable("userAssets");
                });

            modelBuilder.Entity("webapi.Models.UserAsset", b =>
                {
                    b.HasOne("webapi.Models.User", "User")
                        .WithMany("UserAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Navigation("UserAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
