// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.CoinPurchaseRequest", b =>
                {
                    b.Property<int>("CoinPurchaseRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoinPurchaseRequestId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("CoinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAssetCoinCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserAssetUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CoinPurchaseRequestId");

                    b.HasIndex("UserAssetUserId", "UserAssetCoinCode");

                    b.ToTable("coinPurchaseRequests");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapi.Models.UserAsset", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("CoinCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("UserAssetId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.HasKey("UserId", "CoinCode");

                    b.ToTable("userAssets");
                });

            modelBuilder.Entity("webapi.Models.CoinPurchaseRequest", b =>
                {
                    b.HasOne("webapi.Models.UserAsset", null)
                        .WithMany("CoinPurchaseRequests")
                        .HasForeignKey("UserAssetUserId", "UserAssetCoinCode");
                });

            modelBuilder.Entity("webapi.Models.UserAsset", b =>
                {
                    b.HasOne("webapi.Models.User", "User")
                        .WithMany("UserAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Navigation("UserAssets");
                });

            modelBuilder.Entity("webapi.Models.UserAsset", b =>
                {
                    b.Navigation("CoinPurchaseRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
